Added the ForestFlow example
atong01/conditional-flow-matching pull request #66
Opened 2023-11-03 20:51 UTC by AlexiaJM

This adds the ForestFlow example. Let me know if the format is okay. I left the pip install for the special library requirements (except for torchcfm, which is assumed installed).

2023-11-06 15:53 UTC, kilianFatras commented
Thank you for your contribution @AlexiaJM! Indeed, the requirements are directly in the notebook. In all other sections of the library, we have a requirement.txt file that users have to install to run specific parts of the library. I would prefer some consistency and adding a requirements.txt file. @atong01 @josephdviviano what is your opinion?

Also, note that I have just added a test to the forest-flow branch. Everything passed on my side. Note that I still have to add tests for the guidance functions.

2023-11-06 16:04 UTC, atong01 commented
We should add optional dependencies. This would make testing easier. Ideally the syntax would be 
`pip install torchcfm`
`pip install torchcfm[forest]`
`pip install torchcfm[image]`
`pip install torchcfm[singlecell]`

2023-11-06 18:31 UTC, AlexiaJM commented
I removed the installs from the notebook. I incremented the torchcfm package version to be able to add some optional requirements. You can manually test it using `pip install .[examples]`. 

I put everything related to examples into 'examples', but feel free to organize it differently.

2023-11-06 22:33 UTC, kilianFatras requested changes

2023-11-06 22:33 UTC, kilianFatras commented on runner-requirements.txt
runner-requirements is a file that is gonna be depreciated. I would move [xgboost, scikit-learn, ForestDiffusion] packages to requirements.txt and change "example" by "forest-flow".

2023-11-06 22:33 UTC, kilianFatras commented on examples/tabular/Tabular_Data_Generation_with_XGBoost_Conditional_Flow_Matching.ipynb
"from ForestDiffusion import ForestDiffusionModel" Are not you doing diffusion here instead of forest-flow?

2023-11-07 15:03 UTC, AlexiaJM commented on runner-requirements.txt
Done

2023-11-07 15:03 UTC, AlexiaJM commented on examples/tabular/Tabular_Data_Generation_with_XGBoost_Conditional_Flow_Matching.ipynb
Its called ForestDiffusionModel sadly, but I changed the colab to import ForestDiffusionModel  as ForestFlowModel.

2023-11-10 15:00 UTC, kilianFatras approved these changes

2023-11-10 15:01 UTC, merged

2023-11-14 00:33 UTC, josephdviviano commented
Sorry I'm late to this. I think it's easiest if you group all optional deps under `.[examples]` as already mentioned, just to make maintenance of your `pyproject.toml` easier. We do something similar in `torchgfn` (we have an optional `.[scripts]` install flag).